### ISSUE TITLE
Broken Caused by: java.net.URISyntaxException: Illegal character in path at index 6: SORRY, YOU'RE NOT AUTHORIZED.

### ISSUE THREAD

**Issue by devcenter** [matthiasn/sse-perf#1]
Problem when running using 
- ubuntu 14.04 
- OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
- OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
- javac 1.7.0_75

The application worked when accessing in port 9000, I can see the "client active total" numbers increasing but the other indicator showing 0 and chart not showing up. 

it worked in Win7 though :), any pointer where should I check? 

Below is the log messages 

[ERROR] [02/12/2015 12:09:34.362] [sse-perf-my-thread-pool-dispatcher-8] [akka:/                                                                                                                                                              /sse-perf/user/WsClientSupervisor/$fm] error while processing Create(-547762189)
4d9dca2c-556c-4e8a-8ef0-62cc66aaff91akka.actor.ActorInitializationException: exc                                                                                                                                                              eption during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:170)
        at akka.actor.ActorCell.create(ActorCell.scala:496)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:351)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:256)
        at akka.dispatch.Mailbox.run(Mailbox.scala:211)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                                                                                                              java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                                                                                                              .java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Illegal character in path at inde                                                                                                                                                              x 6: SORRY, YOU'RE NOT AUTHORIZED.
        at java.net.URI.create(URI.java:859)
        at com.ning.http.client.RequestBuilderBase.buildUrl(RequestBuilderBase.j                                                                                                                                                              ava:343)
        at com.ning.http.client.RequestBuilderBase.setUrl(RequestBuilderBase.jav                                                                                                                                                              a:328)
        at play.api.libs.ws.WS$WSRequest.setUrl(WS.scala:226)
        at play.api.libs.ws.WS$WSRequestHolder.prepare(WS.scala:426)
        at play.api.libs.ws.WS$WSRequestHolder.get(WS.scala:367)
        at akka.WsClient.<init>(Metrics.scala:112)
        at akka.Supervisor$$anonfun$receive$1$$anonfun$applyOrElse$1$$anonfun$2.                                                                                                                                                              apply(Metrics.scala:63)
        at akka.Supervisor$$anonfun$receive$1$$anonfun$applyOrElse$1$$anonfun$2.                                                                                                                                                              apply(Metrics.scala:63)
        at akka.actor.ActorCell.newActor(ActorCell.scala:461)
        at akka.actor.ActorCell.create(ActorCell.scala:479)
        ... 6 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 6: SO                                                                                                                                                              RRY, YOU'RE NOT AUTHORIZED.
        at java.net.URI$Parser.fail(URI.java:2829)
        at java.net.URI$Parser.checkChars(URI.java:3002)
        at java.net.URI$Parser.parseHierarchical(URI.java:3086)
        at java.net.URI$Parser.parse(URI.java:3044)
        at java.net.URI.<init>(URI.java:595)
        at java.net.URI.create(URI.java:857)
        ... 16 more

**Comment by devcenter** [comment]
you can see it here http://ctmtrade.continentum.com:9000/

**Comment by devcenter** [comment]
sorry, find the problems
1. need to start mongod (mongo db) first and make sure it run without any error (mine showing non existant data path error) 
2. need to restart the application being tested, somehow it still worked but not responsive

**Comment by matthiasn** [comment]
Cool thank you for seeing this through until the problem was solved and also reporting the solution. I have not used this application in a while. Would you like to update it to the latest version of Play? I'd be happy to merge that. Cheers!
